schema_version = "1.0.0"

blender_version_min = "4.5.0"
id = "printing_helper"
license = ["SPDX:GPL-3.0-or-later", ]
maintainer = "ACGGIT Community(小萌新)"
name = "Printing Helper"
tagline = "Set the resolution required for printing more simply"
type = "add-on"
version = "0.1.1"
tags = ["Render", "Camera"]

